ファイルを上書き保存
Sub SaveWorkbook()
    Dim　filePath As String
    Dim fileName As String
    
    ' ファイルパスとファイル名を指定
    filePath = "D:\work\"
    fileName = ThisWorkbook.Name
    
    ' 既存のファイルがあれば上書き保存
    Application.DisplayAlerts = False
    On Error Resume Next
    ThisWorkbook.SaveAs filePath & fileName
    On Error GoTo 0
    Application.DisplayAlerts = True
    
    ' メッセージボックスを表示
    If Err.Number = 0 Then
        MsgBox "ファイルが保存されました。", vbInformation
    Else
        MsgBox "ファイルの保存中にエラーが発生しました。", vbExclamation
    End If
End Sub


ファイルコピーを作成
Sub CopyFileToDirectory()
    Dim SourcePath As String
    Dim DestinationPath As String
    Dim FileName As String
    
    ' 元のディレクトリのパスを取得
    SourcePath = ThisWorkbook.Path
    
    ' コピー先のディレクトリのパスを指定
    DestinationPath = "D:\work\"
    
    ' ファイル名を取得
    FileName = ThisWorkbook.Name
    
    ' ファイルをコピー
    On Error Resume Next
    FileCopy SourcePath & "\" & FileName, DestinationPath & FileName
    On Error GoTo 0
    
    ' エラーチェック
    If Err.Number = 0 Then
        MsgBox "ファイルがコピーされました。"
    Else
        MsgBox "ファイルのコピー中にエラーが発生しました。"
    End If
End Sub

