Sub SaveWorkbook()
    Dim filePath As String
    Dim fileName As String
    
    ' ファイルパスとファイル名を指定
    filePath = "D:\work\"
    fileName = ThisWorkbook.Name
    
    ' 既存のファイルがあれば上書き保存
    Application.DisplayAlerts = False
    On Error Resume Next
    ThisWorkbook.SaveAs filePath & fileName
    On Error GoTo 0
    Application.DisplayAlerts = True
    
    ' メッセージボックスを表示
    If Err.Number = 0 Then
        MsgBox "ファイルが保存されました。", vbInformation
    Else
        MsgBox "ファイルの保存中にエラーが発生しました。", vbExclamation
    End If
End Sub
